apiVersion: v1
kind: ServiceAccount
metadata:
  name: learning-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: learning-role
rules:
  - apiGroups: [""]
    resources:
      [
        "pods",
        "services",
        "endpoints",
        "persistentvolumeclaims",
        "secrets",
        "configmaps",
        "Deployment",
        "StatefulSet",
      ]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: learning-rolebinding
subjects:
  - kind: ServiceAccount
    name: learning-sa
    namespace: default
roleRef:
  kind: Role
  name: learning-role
  apiGroup: rbac.authorization.k8s.io
---

